### Get all notes
GET http://localhost:3001/api/notes

### Get single note
GET http://localhost:3001/api/notes/696d1d460582bdfb3436e846

### Create note
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11c3RhZmEiLCJpZCI6IjY5OTc4NTJjOWE3MzNiNGNlMWM4NjhmNiIsImlhdCI6MTc3MTYxOTQxNX0.44nuE04uLHSdqSpTUJkdnIaxI4iyjQMaVQ23r39N0Zs

{
    "content": "testing to the user id I",
    "important": false,
    "userId": "69934b9bdc27fcb774a2c108"
}

### Update note
PUT http://localhost:3001/api/notes/696f4290397481d00e9e5579
Content-Type: application/json

{
    "content": "testing0",
    "important": "true"
}

### Delete note
DELETE http://localhost:3001/api/notes/6985dd04d0c9cc9e4c503582
