### Get all notes
GET http://localhost:3001/api/notes

### Get single note
GET http://localhost:3001/api/notes/696d1d460582bdfb3436e846

### Create note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "testing",
    "important": false
}

### Update note
PUT http://localhost:3001/api/notes/696f4290397481d00e9e5579
Content-Type: application/json

{
    "content": "testing0",
    "important": "true"
}

### Delete note
DELETE http://localhost:3001/api/notes/696f671108e4baba2d9f5e03
